---
- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: enable schema registry service
  become: true
  systemd:
    name: schema-registry.service
    enabled: true
    masked: no

- name: start schema registry service
  become: true
  systemd:
    name: schema-registry.service
    state: started
    enabled: true