---
- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: enable zookeeper service
  become: true
  systemd:
    name: zookeeper.service
    enabled: true
    masked: no
    
- name: start zookeeper service
  become: true
  throttle: 1
  systemd:
    name: zookeeper.service
    state: started
    enabled: true