{
 "title": "Zookeeper Cluster Dashboard",
 "description": "Metrics was extracted from jmx-exporter that reads JMX data from JVM based applications and exposes it via HTTP in a simple text format that Prometheus understand and can scrape. This dashboard was built for Zookeeper 3.5 version deployment in Local Cluster. You can select metrics based on Job & instance. This dashboard gives cross cluster zookeeper nodes information. It provides Quorum Size, Number of Followers, Member Type information, Healthcheck, Zookeeper metrics and JVM metics.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(process_start_time_seconds{job=\"$namespace\"}, instance)"
   },
   { "name": "namespace", "label": "Namespace", "query": "zookeeper" },
   {
    "name": "application",
    "label": "Application Name",
    "query": "query_result(process_start_time_seconds{_namespace_=\"$namespace\"})"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "query_result(process_start_time_seconds{_namespace_=\"$namespace\", application=\"$application\"})"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quorum Size",
   "type": "singlestat",
   "description": "Quorum formed by zk nodes",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "WOW": [
      {
       "checked": false,
       "label": "-1W",
       "offset": 604800000
      },
      {
       "checked": false,
       "label": "-2W",
       "offset": 1209600000
      },
      {
       "checked": false,
       "label": "-3W",
       "offset": 1814400000
      }
     ],
     "aggregator": "COUNT",
     "dataType": "METRICS",
     "expr": "avg(zookeeper_QuorumSize{ instance=~\"[[instance]]\", job=\"$namespace\"})",
     "funcByType": "dimension"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "singlestat",
   "description": "number of followers within the ensemble. You can deduce the number of servers from the MBeam Quorum Size.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "WOW": [
      {
       "checked": false,
       "label": "-1W",
       "offset": 604800000
      },
      {
       "checked": false,
       "label": "-2W",
       "offset": 1209600000
      },
      {
       "checked": false,
       "label": "-3W",
       "offset": 1814400000
      }
     ],
     "aggregator": "COUNT",
     "dataType": "METRICS",
     "expr": "avg(zookeeper_QuorumSize{instance=~\"[[instance]]\", job=\"$namespace\"}) -1 ",
     "funcByType": "dimension"
    }
   ]
  },
  {
   "title": "Member Type",
   "type": "grafana-piechart-panel",
   "description": "Leader otrFollowers",
   "gridPos": { "h": 5, "w": 16, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "WOW": [
      {
       "checked": false,
       "label": "-1W",
       "offset": 604800000
      },
      {
       "checked": false,
       "label": "-2W",
       "offset": 1209600000
      },
      {
       "checked": false,
       "label": "-3W",
       "offset": 1814400000
      }
     ],
     "aggregator": "COUNT",
     "dataType": "METRICS",
     "expr": "zookeeper_AvgRequestLatency{ instance=~\"[[instance]]\", job=\"$namespace\"} ",
     "funcByType": "dimension",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Health Check (Ticktime)",
   "type": "graph",
   "description": "the length of a single tick, which is the basic time unit used by ZooKeeper, as measured in milliseconds. It is used to regulate heartbeats, and timeouts. For example, the minimum session timeout will be two ticks.",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "ticks" }
   ],
   "targets": [
    {
     "expr": "avg(zookeeper_TickTime{instance=~\"[[instance]]\", job=\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.AvgRequestLatency, 4, 6)"
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Avg Request Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "ticks" }
   ],
   "targets": [
    {
     "expr": "zookeeper_AvgRequestLatency{instance=~\"[[instance]]\", job=\"$namespace\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.AvgRequestLatency, 4, 6)"
    }
   ]
  },
  {
   "title": "Znodes count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_InMemoryDataTree_NodeCount{instance=~\"[[instance]]\", job=\"$namespace\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_NumAliveConnections{instance=~\"[[instance]]\", job=\"$namespace\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.NumAliveConnections, 4, 6)"
    }
   ]
  },
  {
   "title": "Pending session revalidations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_PendingRevalidationCount{instance=~\"[[instance]]\", job=\"$namespace\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_OutstandingRequests{instance=~\"[[instance]]\", job=\"$namespace\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  {
   "title": "Watch count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_InMemoryDataTree_WatchCount{instance=~\"[[instance]]\", job=\"$namespace\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=~\"[[instance]]\", job=\"$namespace\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}",
     "target": "aliasByNode(nonNegativeDerivative(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.sun_management_GarbageCollectorImpl.PSScavenge.CollectionTime.upper), 4)"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{instance=~\"[[instance]]\", job=\"$namespace\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}",
     "target": "aliasByNode(nonNegativeDerivative(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.sun_management_GarbageCollectorImpl.PSMarkSweep.CollectionCount.upper), 4)"
    }
   ]
  },
  {
   "title": "Heap Used vs Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"[[instance]]\", job=\"$namespace\", area=\"heap\"}",
     "legendFormat": "{{instance}} used",
     "target": "aliasByNode(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.memory.HeapMemoryUsage_used.upper, 4, 6)"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=~\"[[instance]]\", job=\"$namespace\", area=\"heap\"}",
     "legendFormat": "{{instance}} max",
     "target": "aliasByNode(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.memory.HeapMemoryUsage_max.upper, 4, 6)"
    }
   ]
  }
 ]
}