---
- name: Grafana configuration
  hosts: grafana
  remote_user: ubuntu
  tasks:
    - name: Install adduser
      become: true
      apt:
        name: adduser
        state: present
        update_cache: yes
    - name: Install libfontconfig1
      become: true
      apt:
        name: libfontconfig1
        state: present
        update_cache: yes
    - name: Download grafana .deb
      become: true
      get_url:
        url: https://dl.grafana.com/enterprise/release/grafana-enterprise_9.4.7_amd64.deb
        dest: /opt/grafana-enterprise_9.4.7_amd64.deb
        mode: 0440
    - name: Install grafana debian package
      become: true
      command: "dpkg -i /opt/grafana-enterprise_9.4.7_amd64.deb"
    - name: Remove grafana .deb
      become: true
      file:
        path: /opt/grafana-enterprise_9.4.7_amd64.deb
        state: absent
    - name: Enable grafana service
      become: true
      systemd:
        name: grafana-server.service
        enabled: true
        masked: no
    - name: Start grafana service
      become: true
      systemd:
        name: grafana-server.service
        state: started
        enabled: true