---
- name: Kafka configuration
  hosts: kafka
  remote_user: ubuntu
  vars:
    data_dir: /opt/kafkadata/kafka-logs
    broker_id: "{{ hostvars[inventory_hostname]['id'] }}"
    private_ip: "{{ hostvars[ inventory_hostname ]['ansible_default_ipv4']['address'] }}"
    zoo_ips: "{{ groups['zoo'] | default([]) | map('extract', hostvars, ['inventory_hostname']) | map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"

  tasks:
  - name: Create sys log directory
    become: true
    file:
      path: "/opt/kafkadata/systemlogs"
      state: directory
      mode: '0755'
  - name: Create app log directory
    become: true
    file:
      path: "/opt/kafkadata/applogs"
      state: directory
      mode: '0755'
  - name: Get public ip for advertiser
    command: curl --silent --fail http://ifconfig.me/ip
    register: public_ip
  - name: Remove existing kafka properties file
    become: true
    file:
      path: /opt/kafka/config/server.properties
      state: absent
  - name: Generate server.properties from template
    become: true
    template:
      src: /opt/ansible-files/server.properties.j2
      dest: /opt/kafka/config/server.properties
  - name: Upload local kafka service file to the servers
    become: true
    copy:
      src: /opt/ansible-files/kafka.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: 0644
#  - name: Upload cruise control metrics exporter to the servers
#    become: true
###   copy:
###     src: /opt/ansible-files/cruise-control-metrics-reporter-2.5.117-SNAPSHOT.jar
###     dest: /opt/kafka/libs/
###     owner: root
###     group: root
###     mode: 0644
  - name: Upload JMX exporter kafka metrics yml file
    become: true
    copy:
      src: /opt/ansible-files/kafka-jmx.yml
      dest: /opt/monitoring/
      owner: root
      group: root
      mode: 0644
  - name: just force systemd to reread configs
    become: true
    systemd:
      daemon_reload: yes
  - name: Download Kafka exporter
    become: true
    get_url:
      url: https://github.com/danielqsj/kafka_exporter/releases/download/v1.6.0/kafka_exporter-1.6.0.linux-amd64.tar.gz
      dest: /tmp/kafka_exporter-1.6.0.linux-amd64.tar.gz
      mode: 0440
  - name: Extract kafka_exporter-1.6.0.linux-amd64.tar.gz
    become: true
    unarchive:
      src: /tmp/kafka_exporter-1.6.0.linux-amd64.tar.gz
      dest: /tmp/
      remote_src: yes
  - name: Move kafka exporter binary to other folder
    become: true
    command: "mv /tmp/kafka_exporter-1.6.0.linux-amd64/kafka_exporter /opt/monitoring/kafka_exporter"
  - name: Remove kafka exporter tar
    become: true
    file:
      path: /tmp/kafka_exporter-1.6.0.linux-amd64.tar.gz
      state: absent
  - name: Generate kafka_exporter.service from template
    become: true
    template:
      src: /opt/ansible-files/kafka_exporter.service.j2
      dest: /etc/systemd/system/kafka_exporter.service
  - name: Enable kafka service
    become: true
    systemd:
      name: kafka.service
      enabled: true
      masked: no
  - name: Enable kafka exporter service
    become: true
    systemd:
      name: kafka_exporter.service
      enabled: true
      masked: no
  # - name: Start kafka service
  #   become: true
  #   systemd:
  #     name: kafka.service
  #     state: started
  #     enabled: true
