---
- name: Mirror Maker Configuration
  hosts: mm
  remote_user: ubuntu
  tasks:
  - name: Create sys log directory
    become: true
    file:
      path: "/opt/mm/applogs"
      state: directory
      mode: '0755'
  - name: Remove existing mirror maker properties file
    become: true
    file:
      path: /opt/kafka/config/connect-mirror-maker.properties
      state: absent
  - name: Upload local mm2 properties file to the server
    become: true
    copy:
      src: /opt/ansible-files/connect-mirror-maker.properties
      dest: /opt/kafka/config/
      owner: root
      group: root
      mode: 0644
  - name: Download JMX exporter connect metrics yml file
    become: true
    get_url:
      url: https://raw.githubusercontent.com/prometheus/jmx_exporter/main/example_configs/kafka-connect.yml
      dest: /opt/monitoring/connect-jmx.yml
      mode: 0440
  - name: Upload local mm2 service file to the server
    become: true
    copy:
      src: /opt/ansible-files/mm.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: 0644
  - name: just force systemd to reread configs
    become: true
    systemd:
      daemon_reload: yes
  - name: Enable mm2 service
    become: true
    systemd:
      name: mm.service
      enabled: true
      masked: no
  - name: Log Rotation
    shell: (crontab -l ; echo '30 2 * * * find /opt/mm/applogs/ -name "connect.log*" ! -name "connect.log" -type f -mtime +7 -exec rm {} \;') | crontab -
  # # - name: Start kafka service
  #   become: true
  #   systemd:
  #     name: kafka.service
  #     state: started
  #     enabled: true
