---
- name: Global Packages
  hosts:
    - kafka
    - zoo
    - mm 
#    - connect
#    - schemareg
#    - cruise
  remote_user: ubuntu
  tasks:
    - name: Update apt repo and cache
      become: true
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      become: true
      apt:
        upgrade: dist
        force_apt_get: yes
    - name: Install openjdk 11
      become: true
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
    - name: Install unzip
      become: true
      apt:
        name: unzip
        state: present
        update_cache: yes
    - name: Install net-tools
      become: true
      apt:
        name: net-tools
        state: present
        update_cache: yes
    - name: Create monitoring directory
      become: true
      file:
        path: "/opt/monitoring"
        state: directory
        mode: '0755'
    - name: Download JMX exporter
      become: true
      get_url:
        url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.18.0/jmx_prometheus_javaagent-0.18.0.jar
        dest: /opt/monitoring/jmx_prometheus_javaagent-0.18.0.jar
        mode: 0440
- name: Kafka Packages
  hosts: 
    - kafka
    - zoo
    - mm
#    - connect
  remote_user: ubuntu
  tasks:
    - name: Download Kafka
      become: true
      get_url:
        url: https://archive.apache.org/dist/kafka/3.3.1/kafka_2.13-3.3.1.tgz
        dest: /opt/kafka_2.13-3.3.1.tgz
        mode: 0440
    - name: Extract kafka_2.13-3.3.1.tgz
      become: true
      unarchive:
        src: /opt/kafka_2.13-3.3.1.tgz
        dest: /opt/
        remote_src: yes
    - name: Rename kafka folder
      become: true
      command: "mv /opt/kafka_2.13-3.3.1 /opt/kafka"
    - name: Remove kafka tar
      become: true
      file:
        path: /opt/kafka_2.13-3.3.1.tgz
        state: absent