---
- name: Prometheus configuration
  hosts: prometheus
  remote_user: ubuntu
  vars:
    kafka_ips: ""
    zoo_ips: ""
    connect_ips: ""
    mm_ips: ""
    kafka_exporter_ips: ""
  tasks:
    - name: Download prometheus tar
      become: true
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
        dest: /opt/prometheus-2.43.0.linux-amd64.tar.gz
        mode: 0440
    - name: Extract prometheus-2.43.0.linux-amd64.tar.gz
      become: true
      unarchive:
        src: /opt/prometheus-2.43.0.linux-amd64.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Rename prometheus folder
      become: true
      command: "mv /opt/prometheus-2.43.0.linux-amd64 /opt/prometheus"
    - name: Remove prometheus tar
      become: true
      file:
        path: /opt/prometheus-2.43.0.linux-amd64.tar.gz
        state: absent
    - name: Create syslog directory
      become: true
      file:
        path: /opt/prometheus/systemlogs
        state: directory
        mode: '0755'
    - name: Generate prometheus config yml file from template
      become: true
      template:
        src: /opt/ansible-files/prometheus-config.yml.j2
        dest: /opt/prometheus/prometheus-config.yml
    - name: Upload local prometheus service file to the servers
      become: true
      copy:
        src: /opt/ansible-files/prometheus.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0644
    - name: Enable Prometheus service
      become: true
      systemd:
        name: prometheus.service
        enabled: true
        masked: no
    - name: Start Prometheus service
      become: true
      systemd:
        name: prometheus.service
        state: started
        enabled: true