---
- name: Provectus Kafka UI Configuration
  hosts:
    - provectus
  remote_user: ubuntu
  vars:
    kafka_ips: "{{ groups['kafka'] | default([]) | map('extract', hostvars, ['inventory_hostname']) | map('regex_replace', '^(.*)$', '\\1:9092') | join(',') }}"
    zoo_ips: "{{ groups['zoo'] | default([]) | map('extract', hostvars, ['inventory_hostname']) | map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"
    connect_ips: "{{ groups['connect'] | default([]) | map('extract', hostvars, ['inventory_hostname']) | map('regex_replace', '^(.*)$', 'http://\\1:8083') | join(',') }}"
  tasks:
    - name: Create provectus directory
      become: true
      file:
        path: "/opt/provectus"
        state: directory
        mode: '0755'
    - name: format the volume to xfs filesystem
      become: true
      shell: mkfs.xfs /dev/xvdf
    - name: mount the volume to data directory
      become: true
      shell: mount /dev/xvdf /opt/provectus/
    - name: Add entry to fstab
      become: true
      shell: echo "/dev/xvdf       /opt/provectus  xfs     defaults        0       0" >> /etc/fstab
    - name: check fstab
      become: true
      shell: mount -a
    - name: Download kafka ui jar
      become: true
      get_url:
        url: https://github.com/provectus/kafka-ui/releases/download/v0.6.0/kafka-ui-api-v0.6.0.jar
        dest: /opt/provectus/kafka-ui-api-v0.6.0.jar
        mode: 0440
    - name: Generate provectus app yml file from template
      become: true
      template:
        src: /opt/ansible-files/provectus-app.yml.j2
        dest: /opt/provectus/provectus-app.yml
    - name: Upload local provectus service file to the servers
      become: true
      copy:
        src: /opt/ansible-files/provectus.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0644
    - name: Enable Provectus Kafka UI service
      become: true
      systemd:
        name: provectus.service
        enabled: true
        masked: no
    - name: Start Provectus service
      become: true
      systemd:
        name: provectus.service
        state: started
        enabled: true
    - name: Logrotate of provectus
      become: true
      copy:
        src: /opt/ansible-files/logrotate/provectus
        dest: /etc/logrotate.d/
        owner: root
        group: root
        mode: 0644