---
- name: Provectus Kafka UI Configuration
  hosts:
    - provectus
  remote_user: ubuntu
  vars:
    kafka_ips: "{{hostvars[groups['kafka'][0]]['inventory_hostname']}}:9092,{{hostvars[groups['kafka'][1]]['inventory_hostname']}}:9092,{{hostvars[groups['kafka'][2]]['inventory_hostname']}}:9092"
    zoo_ips: "{{hostvars[groups['zoo'][0]]['inventory_hostname']}}:2181,{{hostvars[groups['zoo'][1]]['inventory_hostname']}}:2181,{{hostvars[groups['zoo'][2]]['inventory_hostname']}}:2181"
    connect_ips: ""
  tasks:
    - name: Update apt repo and cache
      become: true
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      become: true
      apt:
        upgrade: dist
        force_apt_get: yes
    - name: Install openjdk 17
      become: true
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
    - name: Install unzip
      become: true
      apt:
        name: unzip
        state: present
        update_cache: yes
    - name: Install net-tools
      become: true
      apt:
        name: net-tools
        state: present
        update_cache: yes
    - name: Create monitoring directory
      become: true
      file:
        path: "/opt/monitoring"
        state: directory
        mode: '0755'
    - name: Download JMX exporter
      become: true
      get_url:
        url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.18.0/jmx_prometheus_javaagent-0.18.0.jar
        dest: /opt/monitoring/jmx_prometheus_javaagent-0.18.0.jar
        mode: 0440
    - name: Create provectus directory
      become: true
      file:
        path: "/opt/provectus"
        state: directory
        mode: '0755'
    - name: Download kafka ui jar
      become: true
      get_url:
        url: https://github.com/provectus/kafka-ui/releases/download/v0.6.0/kafka-ui-api-v0.6.0.jar
        dest: /opt/provectus/kafka-ui-api-v0.6.0.jar
        mode: 0440
    - name: Generate provectus app yml file from template
      become: true
      template:
        src: /opt/ansible-files/provectus-app.yml.j2
        dest: /opt/provectus/provectus-app.yml
    - name: Upload local provectus service file to the servers
      become: true
      copy:
        src: /opt/ansible-files/provectus.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0644
    - name: Enable Provectus Kafka UI service
      become: true
      systemd:
        name: provectus.service
        enabled: true
        masked: no
    - name: Start Provectus service
      become: true
      systemd:
        name: provectus.service
        state: started
        enabled: true