---
- name: Schema Registry configuration
  hosts: schemareg
  remote_user: ubuntu
  vars:
    kafka_ips: "{{ groups['kafka'] | default([]) | map('extract', hostvars, ['inventory_hostname']) | map('regex_replace', '^(.*)$', '\\1:9092') | join(',') }}"
  tasks:
  - name: Create schemareg directory
    become: true
    file:
      path: "/opt/schemareg"
      state: directory
      mode: '0755'
  - name: format the volume to xfs filesystem
    become: true
    shell: mkfs.xfs /dev/xvdf
  - name: mount the volume to data directory
    become: true
    shell: mount /dev/xvdf /opt/schemareg/
  - name: Add entry to fstab
    become: true
    shell: echo "/dev/xvdf       /opt/schemareg  xfs     defaults        0       0" >> /etc/fstab
  - name: check fstab
    become: true
    shell: mount -a
  - name: Create sys log directory
    become: true
    file:
      path: "/opt/schemareg/systemlogs"
      state: directory
      mode: '0755'
  - name: Download Apicurio
    become: true
    get_url:
      url: https://github.com/Apicurio/apicurio-registry/releases/download/2.4.1.Final/apicurio-registry-storage-kafkasql-2.4.1.Final-all.tar.gz
      dest: /opt/schemareg/apicurio-registry-storage-kafkasql-2.4.1.Final-all.tar.gz
      mode: 0440
  - name: Extract apicurio-registry-storage-kafkasql-2.4.1.Final-all.tar.gz
    become: true
    unarchive:
      src: /opt/schemareg/apicurio-registry-storage-kafkasql-2.4.1.Final-all.tar.gz
      dest: /opt/schemareg/
      remote_src: yes
  - name: Generate schema-registry.service from template
    become: true
    template:
      src: /opt/ansible-files/schema-registry.service.j2
      dest: /etc/systemd/system/schema-registry.service
  - name: just force systemd to reread configs
    become: true
    systemd:
      daemon_reload: yes
  - name: Enable schema registry service
    become: true
    systemd:
      name: schema-registry.service
      enabled: true
      masked: no
  - name: Remove tar file
    become: true
    file:
      path: /opt/schemareg/apicurio-registry-storage-kafkasql-2.4.1.Final-all.tar.gz
      state: absent
  - name: Logrotate of schemareg
    become: true
    copy:
      src: /opt/ansible-files/logrotate/schemareg
      dest: /etc/logrotate.d/
      owner: root
      group: root
      mode: 0644