---
- name: Zookeeper configuration
  hosts: zoo
  remote_user: ubuntu
  vars:
    data_dir: /opt/zookeeperdata/
    host_num: "{{ groups['zoo'] | length | int}}"
  tasks:
  - name: vars
    set_fact:
      "zookeeper{{ item + 1  }}_ip": "{{ hostvars[groups['zoo'][item]]['inventory_hostname'] }}"
    loop: "{{ range(0,host_num | int) | list }}"
  - name: Create data directory
    become: true
    file:
      path: "{{ data_dir }}"
      state: directory
      mode: '0755'
  - name: Create app log directory
    become: true
    file:
      path: "{{ data_dir }}/applogs"
      state: directory
      mode: '0755'
  - name: Remove existing zookeeper properties file
    become: true
    file:
      path: /opt/kafka/config/zookeeper.properties
      state: absent
  - name: Generate zookeeper.properties from template
    become: true
    template:
      src: /opt/ansible-files/zookeeper.properties.j2
      dest: /opt/kafka/config/zookeeper.properties
  - name: Upload local zookeeper service file to the servers
    become: true
    copy:
      src: /opt/ansible-files/zookeeper.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: 0644
  - name: Download JMX exporter zookeeper metrics yml file
    become: true
    get_url:
      url: https://raw.githubusercontent.com/prometheus/jmx_exporter/main/example_configs/zookeeper.yaml
      dest: /opt/monitoring/zookeeper.yaml
      mode: 0440
  - name: just force systemd to reread configs
    become: true
    systemd:
      daemon_reload: yes
  - name: Write myid to myid file
    become: true
    shell: "echo {{ hostvars[inventory_hostname]['id'] }} > {{ data_dir }}myid"
  - name: Enable zookeeper service
    become: true
    systemd:
      name: zookeeper.service
      enabled: true
      masked: no
  - name: Log Rotation
    shell: (crontab -l ; echo '30 2 * * * find /opt/zookeeperdata/applogs/ -name "server.log*" ! -name "server.log" -type f -mtime +7 -exec rm {} \;') | crontab -
  # - name: Start zookeeper service
  #   become: true
  #   systemd:
  #     name: zookeeper.service
  #     state: started
  #     enabled: true
