---
- name: Zookeeper configuration
  hosts: zoo
  remote_user: ubuntu
  vars:
    data_dir: /opt/zookeeperdata/
    host_num: "{{ groups['zoo'] | length | int}}"
  tasks:
  - name: vars
    set_fact:
      "zookeeper{{ item + 1  }}_ip": "{{ hostvars[groups['zoo'][item]]['inventory_hostname'] }}"
    loop: "{{ range(0,host_num | int) | list }}"
  - name: Create data directory
    become: true
    file:
      path: "{{ data_dir }}"
      state: directory
      mode: '0755'
  - name: format the volume to xfs filesystem
    become: true
    shell: mkfs.xfs /dev/xvdf
  - name: mount the volume to data directory
    become: true
    shell: mount /dev/xvdf /opt/zookeeperdata/
  - name: Add entry to fstab
    become: true
    shell: echo "/dev/xvdf       /opt/zookeeperdata      xfs     defaults        0       0" >> /etc/fstab
  - name: check fstab
    become: true
    shell: mount -a
  - name: Create sys log directory
    become: true
    file:
      path: "{{ data_dir }}/syslogs"
      state: directory
      mode: '0755'
  - name: Create sys log directory
    become: true
    file:
      path: "{{ data_dir }}/log4jlogs"
      state: directory
      mode: '0755'
  - name: Remove existing zookeeper properties file
    become: true
    file:
      path: /opt/kafka/config/zookeeper.properties
      state: absent
  - name: Generate zookeeper.properties from template
    become: true
    template:
      src: /opt/ansible-files/zookeeper.properties.j2
      dest: /opt/kafka/config/zookeeper.properties
  - name: Upload local zookeeper service file to the servers
    become: true
    copy:
      src: /opt/ansible-files/zookeeper.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: 0644
  - name: Download JMX exporter zookeeper metrics yml file
    become: true
    get_url:
      url: https://raw.githubusercontent.com/prometheus/jmx_exporter/main/example_configs/zookeeper.yaml
      dest: /opt/monitoring/zookeeper.yaml
      mode: 0440
  - name: just force systemd to reread configs
    become: true
    systemd:
      daemon_reload: yes
  - name: Write myid to myid file
    become: true
    shell: "echo {{ hostvars[inventory_hostname]['id'] }} > {{ data_dir }}myid"
  - name: Enable zookeeper service
    become: true
    systemd:
      name: zookeeper.service
      enabled: true
      masked: no
  - name: Log Rotation
    become: true
    shell: (crontab -l ; echo '30 1 * * 0 find /opt/zookeeperdata/log4jlogs/ -name "*.log.*" ! -name "*.log" -type f -mtime +7 -exec rm {} \;') | crontab -
  - name: Logrotate for zookeeper
    become: true
    copy:
      src: /opt/ansible-files/logrotate/zookeeper
      dest: /etc/logrotate.d/
      owner: root
      group: root
      mode: 0644