---
- name: Create mm directory
  become: true
  file:
    path: "/opt/mm"
    state: directory
    mode: '0755'
- name: format the volume to xfs filesystem
  become: true
  shell: mkfs.xfs /dev/xvdf
- name: mount the volume to data directory
  become: true
  shell: mount /dev/xvdf /opt/mm/
- name: Add entry to fstab
  become: true
  shell: echo "/dev/xvdf       /opt/mm         xfs     defaults        0       0" >> /etc/fstab
- name: check fstab
  become: true
  shell: mount -a
- name: Create sys log directory
  become: true
  file:
    path: "/opt/mm/syslogs"
    state: directory
    mode: '0755'
- name: Create log4j log directory
  become: true
  file:
    path: "/opt/mm/log4jlogs"
    state: directory
    mode: '0755'
- name: Remove existing mirror maker properties file
  become: true
  file:
    path: /opt/kafka/config/connect-mirror-maker.properties
    state: absent
- name: Upload local mm2 properties file to the server
  become: true
  copy:
    src: ../files/connect-mirror-maker.properties
    dest: /opt/kafka/config/
    owner: root
    group: root
    mode: 0644
- name: Download JMX exporter connect metrics yml file
  become: true
  get_url:
    url: https://raw.githubusercontent.com/prometheus/jmx_exporter/main/example_configs/kafka-connect.yml
    dest: /opt/monitoring/connect-jmx.yml
    mode: 0440
- name: Upload local mm2 service file to the server
  become: true
  copy:
    src: ../files/mm.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd reload
    - enable mirrormaker service
- name: Log Rotation
  become: true
  shell: (crontab -l ; echo '30 1 * * 0 find /opt/mm/log4jlogs/ -name "*.log.*" ! -name "*.log" -type f -mtime +7 -exec rm {} \;') | crontab -
- name: Logrotate of mirrormaker
  become: true
  copy:
    src: ../files/mirrormaker
    dest: /etc/logrotate.d/
    owner: root
    group: root
    mode: 0644