---
- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes
      
- name: enable connect service
  become: true
  systemd:
    name: connect.service
    enabled: true
    masked: no

- name: start connect service
  become: true
  systemd:
    name: connect.service
    state: started
    enabled: true