---
data_dir: /opt/kafkadata/data
broker_id: "{{ hostvars[inventory_hostname]['id'] }}"
private_ip: "{{ hostvars[ inventory_hostname ]['ansible_default_ipv4']['address'] }}"
zoo_ips: "{{ groups['zoo'] | default([]) | map('extract', hostvars, ['inventory_hostname']) | map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"