---
- name: enable grafana service
  become: true
  systemd:
    name: grafana-server.service
    enabled: true
    masked: no

- name: start grafana service
  become: true
  systemd:
    name: grafana-server.service
    state: started
    enabled: true