---
- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: enable cruise control service
  become: true
  systemd:
    name: cruise.service
    enabled: true
    masked: no
    
- name: start cruise control service
  become: true
  systemd:
    name: cruise.service
    state: started
    enabled: true