---
- name: Update apt repo and cache
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
- name: Upgrade all packages
  become: true
  apt:
    upgrade: dist
    force_apt_get: yes
- name: Install extra software packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - openjdk-17-jdk
    - unzip
    - net-tools
- name: Create monitoring directory
  become: true
  file:
    path: "/opt/monitoring"
    state: directory
    mode: '0755'
- name: Download JMX exporter
  become: true
  get_url:
    url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.18.0/jmx_prometheus_javaagent-0.18.0.jar
    dest: /opt/monitoring/jmx_prometheus_javaagent-0.18.0.jar
    mode: 0440